### ISSUE TITLE
Catalog: Red Hat repository doesn't get added automatically

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto#1597]
### Describe the Bug

When generating the Kaoto catalog for the Red Hat build of Apache Camel, the Red Hat repository is not added automatically, despite [having the code for it](https://github.com/KaotoIO/kaoto/blob/391c3439ebaed2f1301071ffc06b62a661ef641b/packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/maven/CamelCatalogVersionLoader.java#L220-L221).

### Steps to Reproduce the Bug or Issue

1. Generate a catalog for the `4.4.0.redhat-00045` version
2. Notice it fails because it cannot find the Camel YAML DSL dependency for that `4.4.0.redhat-00045` version

**Comment by apupier** [comment]
```
SEVERE: Camel YAML DSL JSON Schema is not loaded
Nov 20, 2024 2:08:40 PM io.kaoto.camelcatalog.generator.CatalogGenerator processCatalog
SEVERE: java.lang.NullPointerException: Cannot invoke "io.kaoto.camelcatalog.generator.CamelYamlDslSchemaProcessor.getDataFormats()" because "this.schemaProcessor" is null
java.lang.NullPointerException: Cannot invoke "io.kaoto.camelcatalog.generator.CamelYamlDslSchemaProcessor.getDataFormats()" because "this.schemaProcessor" is null
        at io.kaoto.camelcatalog.generator.CamelCatalogProcessor.getDataFormatCatalog(CamelCatalogProcessor.java:210)
        at io.kaoto.camelcatalog.generator.CamelCatalogProcessor.processCatalog(CamelCatalogProcessor.java:72)
        at io.kaoto.camelcatalog.generator.CatalogGenerator.processCatalog(CatalogGenerator.java:187)
        at io.kaoto.camelcatalog.generator.CatalogGenerator.generate(CatalogGenerator.java:70)
        at io.kaoto.camelcatalog.commands.GenerateCommand.lambda$0(GenerateCommand.java:52)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at io.kaoto.camelcatalog.commands.GenerateCommand.run(GenerateCommand.java:36)
        at io.kaoto.camelcatalog.Main.main(Main.java:28)

Nov 20, 2024 2:08:42 PM io.kaoto.camelcatalog.commands.GenerateCommand lambda$0
INFO: Generating catalog: Quarkus 3.8.0.redhat-00006

Nov 20, 2024 2:08:47 PM io.kaoto.camelcatalog.generator.CatalogGenerator processCamelSchema
SEVERE: Camel YAML DSL JSON Schema is not loaded
Nov 20, 2024 2:08:47 PM io.kaoto.camelcatalog.generator.CatalogGenerator processCatalog
SEVERE: java.lang.NullPointerException: Cannot invoke "io.kaoto.camelcatalog.generator.CamelYamlDslSchemaProcessor.getDataFormats()" because "this.schemaProcessor" is null
java.lang.NullPointerException: Cannot invoke "io.kaoto.camelcatalog.generator.CamelYamlDslSchemaProcessor.getDataFormats()" because "this.schemaProcessor" is null
        at io.kaoto.camelcatalog.generator.CamelCatalogProcessor.getDataFormatCatalog(CamelCatalogProcessor.java:210)
        at io.kaoto.camelcatalog.generator.CamelCatalogProcessor.processCatalog(CamelCatalogProcessor.java:72)
        at io.kaoto.camelcatalog.generator.CatalogGenerator.processCatalog(CatalogGenerator.java:187)
        at io.kaoto.camelcatalog.generator.CatalogGenerator.generate(CatalogGenerator.java:70)
        at io.kaoto.camelcatalog.commands.GenerateCommand.lambda$0(GenerateCommand.java:52)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at io.kaoto.camelcatalog.commands.GenerateCommand.run(GenerateCommand.java:36)
        at io.kaoto.camelcatalog.Main.main(Main.java:28)

Nov 20, 2024 2:08:49 PM io.kaoto.camelcatalog.commands.GenerateCommand lambda$0
INFO: Generating catalog: SpringBoot 4.4.0.redhat-00014

Nov 20, 2024 2:09:02 PM io.kaoto.camelcatalog.generator.CatalogGenerator processCamelSchema
SEVERE: Camel YAML DSL JSON Schema is not loaded
Nov 20, 2024 2:09:02 PM io.kaoto.camelcatalog.generator.CatalogGenerator processCatalog
SEVERE: java.lang.NullPointerException: Cannot invoke "io.kaoto.camelcatalog.generator.CamelYamlDslSchemaProcessor.getDataFormats()" because "this.schemaProcessor" is null
java.lang.NullPointerException: Cannot invoke "io.kaoto.camelcatalog.generator.CamelYamlDslSchemaProcessor.getDataFormats()" because "this.schemaProcessor" is null
        at io.kaoto.camelcatalog.generator.CamelCatalogProcessor.getDataFormatCatalog(CamelCatalogProcessor.java:210)
        at io.kaoto.camelcatalog.generator.CamelCatalogProcessor.processCatalog(CamelCatalogProcessor.java:72)
        at io.kaoto.camelcatalog.generator.CatalogGenerator.processCatalog(CatalogGenerator.java:187)
        at io.kaoto.camelcatalog.generator.CatalogGenerator.generate(CatalogGenerator.java:70)
        at io.kaoto.camelcatalog.commands.GenerateCommand.lambda$0(GenerateCommand.java:52)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at io.kaoto.camelcatalog.commands.GenerateCommand.run(GenerateCommand.java:36)
        at io.kaoto.camelcatalog.Main.main(Main.java:28)
 ```

**Comment by lhein** [comment]
the repo gets added correctly when I debugged it, so the issue must be something else
