### ISSUE TITLE
Received the string `false` for the boolean attribute `checked`. The browser will interpret it as a truthy value. Did you mean checked={false}?

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto#1639]
### Describe the Bug

in log there is this error:

```
hook.js:608 Warning: Received the string `false` for the boolean attribute `checked`. The browser will interpret it as a truthy value. Did you mean checked={false}? Error Component Stack
    at input (<anonymous>)
    at div (<anonymous>)
    at _Checkbox (@kaoto-next_uniforms…s?v=055e2475:3530:9)
    at div (<anonymous>)
    at div (<anonymous>)
    at div (<anonymous>)
    at GenerateId (@kaoto-next_uniforms…js?v=055e2475:837:9)
    at FormGroup2 (@kaoto-next_uniforms…?v=055e2475:4146:13)
    at BoolField (@kaoto-next_uniforms…?v=055e2475:23749:9)
    at Field (chunk-AKYERLJH.js?v=055e2475:1620:51)
    at AutoField (chunk-AKYERLJH.js?v=055e2475:1640:38)
    at div (<anonymous>)
    at CardBody (chunk-OKIQ5TPJ.js?v=055e2475:13210:9)
    at div (<anonymous>)
    at Card (chunk-OKIQ5TPJ.js?v=055e2475:13141:9)
    at CustomNestField.tsx:41:5
    at Field (chunk-AKYERLJH.js?v=055e2475:1620:51)
    at AutoField (chunk-AKYERLJH.js?v=055e2475:1640:38)
    at AutoField (chunk-AKYERLJH.js?v=055e2475:1640:38)
    at div (<anonymous>)
    at CustomAutoFields (CustomAutoFields.tsx:21:3)
    at form (<anonymous>)
    at FormBase (@kaoto-next_uniforms…?v=055e2475:3766:13)
    at Form (<anonymous>)
    at AutoValidatedQuickPatternflyForm (<anonymous>)
    at CustomAutoForm.tsx:21:28
    at SchemaBridgeProvider (schema-bridge.provider.tsx:22:13)
    at CanvasFormBody (CanvasFormBody.tsx:18:27)
    at div (<anonymous>)
    at CardBody (chunk-OKIQ5TPJ.js?v=055e2475:13210:9)
    at div (<anonymous>)
    at Card (chunk-OKIQ5TPJ.js?v=055e2475:13141:9)
    at ErrorBoundary (ErrorBoundary.tsx:18:5)
    at CanvasForm (CanvasForm.tsx:15:66)
    at FilteredFieldProvider (filtered-field.provider.tsx:19:39)
    at ErrorBoundary (ErrorBoundary.tsx:18:5)
    at div (<anonymous>)
    at TopologySideBar (@patternfly_react-to…?v=055e2475:10025:9)
    at CanvasSideBar (CanvasSideBar.tsx:15:13)
    at div (<anonymous>)
    at div (<anonymous>)
    at GenerateId (chunk-OKIQ5TPJ.js?v=055e2475:8306:5)
    at DrawerPanelContent (chunk-OKIQ5TPJ.js?v=055e2475:15416:9)
    at div (<anonymous>)
    at DrawerMain (chunk-OKIQ5TPJ.js?v=055e2475:15325:9)
    at DrawerContent (chunk-OKIQ5TPJ.js?v=055e2475:15332:9)
    at div (<anonymous>)
    at Drawer (chunk-OKIQ5TPJ.js?v=055e2475:15271:9)
    at div (<anonymous>)
    at StackItem (chunk-OKIQ5TPJ.js?v=055e2475:24927:9)
    at div (<anonymous>)
    at Stack (chunk-OKIQ5TPJ.js?v=055e2475:24915:9)
    at TopologyView (@patternfly_react-to…s?v=055e2475:9776:9)
    at Canvas (Canvas.tsx:47:77)
    at ErrorBoundary (ErrorBoundary.tsx:18:5)
    at CanvasFormTabsProvider (canvas-form-tabs.provider.tsx:15:41)
    at div (<anonymous>)
    at VisualizationProvider (@patternfly_react-to…v=055e2475:16997:32)
    at Visualization (Visualization.tsx:19:22)
    at ActionConfirmationModalContextProvider (action-confirmation-….provider.tsx:28:41)
    at CatalogModalProvider (catalog-modal.provider.tsx:42:31)
    at DesignPage (DesignPage.tsx:9:27)
    at RenderedRoute (react-router-dom.js?v=055e2475:3637:5)
    at Outlet (react-router-dom.js?v=055e2475:4007:26)
    at VisibleFlowsProvider (visible-flows.provider.tsx:18:27)
    at CatalogTilesProvider (catalog-tiles.provider.tsx:14:26)
    at CatalogLoaderProvider (catalog.provider.tsx:16:45)
    at SchemasLoaderProvider (schemas.provider.tsx:17:45)
    at RuntimeProvider (runtime.provider.tsx:22:45)
    at div (<anonymous>)
    at PanelMainBody (chunk-OKIQ5TPJ.js?v=055e2475:16480:9)
    at div (<anonymous>)
    at PanelMain (chunk-OKIQ5TPJ.js?v=055e2475:16469:9)
    at div (<anonymous>)
    at PanelBase (chunk-OKIQ5TPJ.js?v=055e2475:16447:9)
    at Panel (<anonymous>)
    at main (<anonymous>)
    at div (<anonymous>)
    at Page (chunk-OKIQ5TPJ.js?v=055e2475:20474:5)
    at Shell (Shell.tsx:13:37)
    at EntitiesProvider (entities.provider.tsx:7:17)
    at SourceCodeProvider (source-code.provider.tsx:22:39)
    at SettingsProvider (settings.provider.tsx:13:49)
    at Provider (reload.hook.tsx:15:50)
    at App (App.tsx:19:26)
    at RenderedRoute (react-router-dom.js?v=055e2475:3637:5)
    at RenderErrorBoundary (react-router-dom.js?v=055e2475:3597:5)
    at DataRoutes (react-router-dom.js?v=055e2475:4746:5)
    at Router (react-router-dom.js?v=055e2475:4014:15)
    at RouterProvider (react-router-dom.js?v=055e2475:4563:5)
```

### Steps to Reproduce the Bug or Issue

1. create a Camel route
2. add a component such as amqp
3. select it
4. click on All in config panel

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]

**Comment by lordrip** [comment]
This was fixed as part of the new form functionality
